[programs.localnet]
membership_auction = "6Zt81sekecE5npwcDSLveAH1Uvs75DfXqaquLbXdPpD1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
